### ISSUE TITLE
Install a tslint.json that extends installed gts' tslint.json like the tsconfig.json does

### ISSUE THREAD

**Issue by usergenic** [google/ts-style#119]
Necessary for IDEs that have tslint integration.  Would also enable extensibility of the tslint config where needed while supporting keeping up-to-date with base config.

**Comment by ofrobots** [comment]
We expose the `tsconfig.json` because it would have been impractical to assume that the needs of all projects can be satisfied with a canned `tsconfig.json`. For example, users typically need to edit the input files, output directories, etc.

The reason why we chose to not expose `tslint.json` is the thinking was that there ought to be very few reason to diverge from the style guide as far as the linting rules are concerned. So while exposing this possible, the intent was to discourage customization / extension.

The use case of IDEs is valid though.

**Comment by hvent90** [comment]
@ofrobots, a desire to allow "any" lead me here, and I was wondering if you'd care to share your thoughts on this:

I want to be as strictly typed as possible. A hypothetical maintainer of an API may request to keep expectations open for how the response may alter or change. How could I avoid using an "any" type here?

I apologize if this is out of line for me to ask this here, but I would be extremely grateful to hear your thoughts!

**Comment by keradus** [comment]
Then even more, let say I want to extend tslint by custom ruleset, eg Codelyzer, and use rules suggested by Angular himself, eg `no-conflicting-life-cycle-hooks` - without ability to adjust `tslint.json`, I can't do it with `ts-style`
