### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by tomitrescak** [google/ts-style#180]
Dears, thanks for a fine tool. Any plans to have this working with tscode? Thanks.

**Comment by andrewtw** [comment]
I'm not sure what's your concern, but this works functionally in my VScode (mac).
After installing the package, `tsconfig` and `tslint` should added the `extends` of `gts` in configuration automatically.

Disclaimer: I'm not the Googler.

**Comment by ofrobots** [comment]
@tomitrescak can you elaborate on what you would like see working that is not working today? As @andrewtw mentioned, this should work okay with vscode and other editors already.

**Comment by tomitrescak** [comment]
Guys, sorry, I misunderstood the way it's applied. I got it running as per instructions. Sorry for wasitng your time!

**Comment by PeteJodo** [comment]
The auto-formatting done on save in VS Code seems to follow a different style than what `gts fix` does but there doesn't seem to be a way to have the auto-formatting use `gts fix` unless you use an extension like `Save and Run` which isn't ideal because the 2 end up clashing. Curious if there's a better way to have it set up?

**Comment by AaronVasquez** [comment]
Any update on how to make this work with `Format On Save`?
