### ISSUE TITLE
Use TypeScript 3

### ISSUE THREAD

**Issue by fhinkel** [google/ts-style#203]
Can we upgrade to TS3? 

```
 npx gts init
npx: installed 174 in 17.821s
Already have devDependency for typescript:
-^3.0.1
+~2.8.0
? Overwrite No
```

**Comment by fhinkel** [comment]
ping @ofrobots

**Comment by carnesen** [comment]
Though 3.0 is a "major" release, [the docs say](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#typescript-30) there is just one breaking change, "The `unknown` keyword is reserved", which I'd guess we are not super likely to encounter in users of this project. What could go wrong?®

**Comment by carnesen** [comment]
See #203

**Comment by fhinkel** [comment]
> What could go wrong?®

We have tests™️.

**Comment by carnesen** [comment]
I thought the title of #208 would result in this issue being [auto-closed](https://help.github.com/articles/closing-issues-using-keywords/). Apparently the "closes #x" phrase must be in the description or in a commit message; title is not sufficient. Anyway, lesson learned. This issue is "fixed" and can be (manually) closed.

**Comment by ofrobots** [comment]
thanks!
