### ISSUE TITLE
Add newline to end of generated tsconfig.json

### ISSUE THREAD

**Issue by JustinBeckwith** [google/ts-style#68]
I used `npx gts init`, and it generated a tsconfig.json for me (awesome).  During that CR, @ofrobots mentioned that it should have a newline at the end. Fixing mine now, but should probably be fixed here :)

Also worth asking - if newlines at the end of a file are a thing we should be doing, shouldn't gts check for that and fix?

**Comment by ofrobots** [comment]
We need https://palantir.github.io/tslint/rules/eofline/.

Next question: does internal tslint config have this.

**Comment by ofrobots** [comment]
@evmar: the internal tslint.json doesn't seem to have this. Objections on adding it there?

**Comment by evmar** [comment]
Please do!  Bring it up with the team!

**Comment by ofrobots** [comment]
There were two issues raised by OP:

* Generated tsconfig.json doesn't contain a terminal newline. PR here: https://github.com/google/ts-style/pull/71.
* Whether `gts check` should warn on a missing terminal new line. It turns out we already have `eofline` in the tslint.json. The reason this wasn't caught is because we don't run tslint on .json files.
